/**
 * Stepped list card — product example.
 *
 * Shows the intended look and behaviour of a finished card: items grouped by
 * date, with previous/next stepping between groups and the current date
 * announced to assistive technology.
 *
 * @remarks
 * This file is a structural and behavioural reference only. It was generated by
 * an agent from an earlier HTML dashboard and has not been reviewed. It is not
 * the pattern to follow when writing a real card template — real card templates
 * pair a component with a schema (see `src/dashboard/card-templates.ts`) and do
 * not carry their own data.
 *
 * Presentation comes from the active theme. This file defines no styles; the
 * class names below are theme hooks only.
 *
 * All data below is placeholder content.
 */

import React, { useState } from "react";
import { Button } from "react-aria-components";

interface Item {
  category: string;
  title: string;
  detail: string;
}

const ITEMS_BY_DATE: Record<string, Item[]> = {
  "2026-01-05": [
    {
      category: "Example category A",
      title: "Example item title",
      detail: "Example supporting detail for this item.",
    },
  ],
  "2026-01-06": [
    {
      category: "Example category A",
      title: "Another example item title",
      detail: "Example supporting detail for this item.",
    },
  ],
  "2026-01-07": [
    {
      category: "Example category A",
      title: "Example item title",
      detail: "Example supporting detail for this item.",
    },
    {
      category: "Example category B",
      title: "Example item from a second category",
      detail: "Example supporting detail for this item.",
    },
  ],
  "2026-01-08": [
    {
      category: "Example category B",
      title: "Example item title",
      detail: "Example supporting detail for this item.",
    },
  ],
};

export function SteppedListCard(): React.ReactElement {
  const dates = Object.keys(ITEMS_BY_DATE).sort();
  const [dateIndex, setDateIndex] = useState(0);

  const currentDate = dates[dateIndex];
  const items = ITEMS_BY_DATE[currentDate] ?? [];

  return (
    <section className="stepped-list-card">
      <header>
        <h2 className="stepped-list-title">Example Card</h2>
      </header>

      <nav aria-label="Date navigation">
        <div className="nav-controls">
          <Button
            isDisabled={dateIndex === 0}
            onPress={() => setDateIndex(dateIndex - 1)}
            aria-label="Previous day"
            className="nav-button"
          >
            ← Previous
          </Button>

          {/* Live region announces date changes to screen readers */}
          <div
            className="date-display"
            role="status"
            aria-live="polite"
            aria-atomic="true"
          >
            <time dateTime={currentDate}>{formatDate(currentDate)}</time>
          </div>

          <Button
            isDisabled={dateIndex === dates.length - 1}
            onPress={() => setDateIndex(dateIndex + 1)}
            aria-label="Next day"
            className="nav-button"
          >
            Next →
          </Button>
        </div>
      </nav>

      <div className="stepped-list-items">
        {items.length > 0 ? (
          items.map((item, index) => (
            <article key={index} className="stepped-list-item">
              <h3 className="item-category">{item.category}</h3>
              <h4 className="item-title">{item.title}</h4>
              <p className="item-detail">{item.detail}</p>
            </article>
          ))
        ) : (
          <p className="stepped-list-empty">No items for this day.</p>
        )}
      </div>

      <footer className="stepped-list-footer">
        <p>Last updated: 2026-01-07 at 2:45 PM</p>
      </footer>
    </section>
  );
}

function formatDate(dateString: string): string {
  return new Date(`${dateString}T00:00:00`).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export default SteppedListCard;
